telemetry: false
sonarrEnabled: false
radarrEnabled: false
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

sonarr:
  sonarrinstance1:
    base_url: http://sonarr:8989
    api_key: !env SONARR_API_KEY
    quality_definition:
      type: series
    include:
#      - template: local-template-name

radarr:
  radarrinstance1:
    base_url: http://radarr:7878
    api_key: !env RADARR_API_KEY
    quality_definition:
      type: movie
    include:
#      - template: local-template-name

