telemetry: false
sonarrEnabled: true
radarrEnabled: false
whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false

# Sonarr Configuration
sonarr:
  instance1: # Instance name (can be any unique identifier)
    base_url: http://sonarr:18989 # Sonarr instance URL
    api_key: !env SONARR_API_KEY # load from environment variable
    quality_definition:
      type: series # Quality definition type for Sonarr
