version: 2
updates:
  - package-ecosystem: "docker"
    directories: 
      - "/"
      - "/media-server"
    schedule:
      interval: "monthly"
    groups:
      all-images:
        patterns:
          - "*"