name: media-server
reference: copilot/add-media-libraries-to-jellyfin
working_dir: media-server/
compose_files:
  - docker-compose.yml
#force_recreate: true
destroy: true
destroy_opts:
  remove_volumes: true
  remove_images: true
  remove_dir: true
env_files:
  - .enc.env

---
name: monitoring
working_dir: monitoring/
compose_files:
  - docker-compose.yml

#---
#name: nfs-test
#working_dir: nfs-test/
#compose_files:
#  - docker-compose.yml
#force_recreate: true

#---
#name: tailscale
#working_dir: tailscale/
#compose_files:
#  - docker-compose.yml
#force_recreate: true
