name: media-server
reference: configarr
working_dir: media-server/
compose_files:
  - docker-compose.yml
force_recreate: false
remove_orphans: true
reconciliation: true
destroy: false
destroy_opts:
  remove_volumes: false
  remove_images: false
  remove_dir: false
env_files:
  - .enc.env

---
name: monitoring
working_dir: monitoring/
compose_files:
  - docker-compose.yml
reconciliation: true

#---
#name: nfs-test
#working_dir: nfs-test/
#compose_files:
#  - docker-compose.yml
#force_recreate: true

#---
#name: tailscale
#working_dir: tailscale/
#compose_files:
#  - docker-compose.yml
#force_recreate: true
